### ISSUE TITLE
Include the assets in the C++ tutorial AppVeyor artifact

### ISSUE THREAD

**Issue by prock-fife** [fifengine/cpp-tutorials#11]
Just downloaded the AppVeyor artifact however it didn't include the assets to be able to run the Tutorial.

**Comment by jakoch** [comment]
Good point.

Ok, to resolve the assets paths, i need to adjust the folder structure of the artifact, too:
Because the assets are expected two folders up: [`defaultFontPath("../../assets/fonts/FreeSans.ttf");`](https://github.com/fifengine/cpp-tutorials/blob/850276422f52476e9a0a0cc53219b44b38832819/src/tutorial_1/Game.cpp#L219).

```
\tutorials
   \- tutorial1
\assets
  \- fonts
  \- etc
```

**Comment by jakoch** [comment]
Here we go: 
https://ci.appveyor.com/api/buildjobs/7vyi0s489vsaxv6o/artifacts/tutorials-dev-c8d7209-VC14.zip
