### ISSUE TITLE
MSVCP140.dll is missing

### ISSUE THREAD

**Issue by prock-fife** [fifengine/cpp-tutorials#13]
I get the error "MSVCP140.dll is missing" when attempting to run the artifact provided by AppVeyor.  Is there a way to statically link the C++ runtime dependencies?  If so, should we be doing that to make the demo more portable?

**Comment by jakoch** [comment]
Well, there is no way to statically link them, but, there is a way to distribute them with the project.
Unfortunately, i couldn't get CPack working, yet. (The produced zip file is empty, except containing the system libs.) That's why the part is commented out.

https://github.com/fifengine/cpp-tutorials/blob/master/src/tutorial_1/CMakeLists.txt#L112-L114

**Comment by jakoch** [comment]
Here we go:
https://ci.appveyor.com/api/buildjobs/15li0srphvd00fae/artifacts/tutorials-dev-d7d65c6-VC14.zip

**Comment by prock-fife** [comment]
Looks good.. now it segfaults but that is another issue.  I will need to dig deeper myself into this.

**Comment by jakoch** [comment]
Indeed, it would be nice, if you find the time to debug this. 
Now, we are here: https://github.com/fifengine/fifengine/issues/907#issuecomment-248749607
